name: Sync Tip Sheets
on:
  workflow_dispatch

jobs:
  sync-tip-sheets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install crcmod
      run: |
        sudo apt-get install gcc python-dev python-setuptools
        sudo pip install -I --no-cache-dir -U crcmod
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud info
    - id: upload-files
      name: Upload tip sheets to Google Cloud Storage (rsync)
      timeout-minutes: 30
      run: gsutil rsync -R -c ./tip_sheets gs://covid-website-pdfs1/assets/tip_sheets
